# For affinity prediction
# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/config.py
# 30x8x8 nm in (z,y,x), 1000x4096x4096 voxel
SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 4
MODEL:
  ARCHITECTURE: 'unet_residual_3d'
  INPUT_SIZE: [32, 256, 256]
  OUTPUT_SIZE: [32, 256, 256]
  IN_PLANES: 1
  OUT_PLANES: 3
  LOSS_OPTION: [['WeightedBCE']]
  TARGET_OPT: ['2']
  WEIGHT_OPT: [['1']]
DATASET:
  IMAGE_NAME: 'im_train.json'
  LABEL_NAME: 'mito_train.json'
  INPUT_PATH: '<path/to/data>'
  OUTPUT_PATH: 'outputs/MitoEM_R_A/'
  PAD_SIZE: [16, 128, 128]
  DO_CHUNK_TITLE: 1
  DATA_CHUNK_NUM: [8, 2, 2]
  DATA_CHUNK_ITER: 2500
  LABEL_EROSION: 1
AUGMENTOR:
  ADDITIONAL_TARGETS_NAME: ['label']
  ADDITIONAL_TARGETS_TYPE: ['mask']
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 5e-04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 50000
  SAMPLES_PER_BATCH: 4
INFERENCE:
  INPUT_SIZE: [32, 256, 256]
  OUTPUT_SIZE: [32, 256, 256]
  IMAGE_NAME: 'im_test.json'
  OUTPUT_PATH: 'outputs/MitoEM_R_A/test/'
  OUTPUT_NAME: 'result.h5'
  PAD_SIZE: [16, 128, 128]
  AUG_MODE: 'mean'
  AUG_NUM: 4
  STRIDE: [16, 128, 128]
  SAMPLES_PER_BATCH: 16