SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
MODEL:
  ARCHITECTURE: unet_plus_3d
  BLOCK_TYPE: residual_se
  INPUT_SIZE: [17, 257, 257]
  OUTPUT_SIZE: [17, 257, 257]
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ["1"] # non-exclusive synaptic masks
  NORM_MODE: gn
  FILTERS: [32, 64, 96, 128, 192]
DATASET:
  IMAGE_NAME:
    - vol3/im_Yx2.h5
    - vol4/im_Yx2.h5
  LABEL_NAME:
    - vol3/syn_Yx2.h5
    - vol4/syn_Yx2.h5
  INPUT_PATH: datasets/JWR15/roi_8x8x3um/
  OUTPUT_PATH: outputs/JWR15_Synapse/
  PAD_SIZE: [4, 48, 48]
  DISTRIBUTED: True
  REJECT_SAMPLING:
    SIZE_THRES: 2000
    P: 0.95
  DATA_CHUNK_NUM: [20, 7, 8] # only for inference
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 200000
  SAMPLES_PER_BATCH: 2
INFERENCE:
  INPUT_SIZE: [33, 257, 257]
  OUTPUT_SIZE: [33, 257, 257]
  OUTPUT_ACT: ["sigmoid"]
  IS_ABSOLUTE_PATH: False
  DO_CHUNK_TITLE: 1
  INPUT_PATH: datasets/JWR15/
  IMAGE_NAME: jwr15.json
  OUTPUT_PATH: outputs/JWR15_Synapse/test
  OUTPUT_NAME: result.h5
  PAD_SIZE: [8, 128, 128]
  AUG_MODE: mean
  AUG_NUM: None
  STRIDE: [16, 128, 128]
  SAMPLES_PER_BATCH: 4
